// <auto-generated />
namespace DataTableAndDTO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtables));
        
        string IMigrationMetadata.Id
        {
            get { return "201708100815290_createtables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
